# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# This menu supports parent-child relationships for dropdown menus.

# About parent menu
[[main]]
  identifier = "about-menu"
  name = "About"
  pageRef = "about"
  weight = 1

[[main]]
  name = "Committee"
  pageRef = "committee"
  parent = "about-menu"
  weight = 2

[[main]]
  name = "Testimonials"
  pageRef = "testimonials"
  parent = "about-menu"
  weight = 3

# Pictures - standalone top-level item
[[main]]
  name = "Pictures"
  pageRef = "galleries"
  weight = 10

# Community parent menu
[[main]]
  identifier = "community-menu"
  name = "Community"
  weight = 11

[[main]]
  name = "Updates"
  pageRef = "posts"
  parent = "community-menu"
  weight = 1

[[main]]
  name = "Instagram"
  url = "https://www.instagram.com/somewhatreunion/?igsh=eTBwZmQwNDhsbzk%3D"
  parent = "community-menu"
  weight = 3
  [main.params]
    icon = "instagram"
    target = "_blank"
    showName = true

[[main]]
  name = "Facebook"
  url = "https://www.facebook.com/groups/somewhatreunion"
  parent = "community-menu"
  weight = 4
  [main.params]
    icon = "facebook"
    target = "_blank"
    showName = true

[[main]]
  name = "Discord"
  url = "https://discord.com/invite/7z7qS2ARez"
  parent = "community-menu"
  weight = 5
  [main.params]
    icon = "discord"
    target = "_blank"
    showName = true

# Top-level items
[[main]]
  name = "Resources"
  pageRef = "resources"
  weight = 20

[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 21

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"
    
    

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10
